using CppTestContextBuilder.Core.Models;
using CppTestContextBuilder.Interfaces;

namespace CppTestContextBuilder.Providers
{
    internal class CppIncludesProvider : ICppIncludesProvider
    {
        public List<Include> Get() => new()
        {
            External("cstring"),
            External("any"),
            External("bitset"),
            External("chrono"),
            External("compare"),
            External("cstdlib"),
            External("ctime"),
            External("functional"),
            External("initializer_list"),
            External("optional"),
            External("source_location"),
            External("tuple"),
            External("type_traits"),
            External("typeindex"),
            External("typeinfo"),
            External("typeinfo"),
            External("utility"),
            External("variant"),
            External("memory_resource"),
            External("new"),
            // External("scoped_allocation"),
            External("cfloat"),
            External("cinttypes"),
            External("climits"),
            External("cstdint"),
            External("limits"),
            // External("stdfloat"),
            External("cassert"),
            External("cerrno"),
            External("exception"),
            External("system_error"),
            External("cctype"),
            External("charconv"),
            External("cuchar"),
            External("cwchar"),
            External("cwctype"),
            // External("format"),
            External("string"),
            External("string_view"),
            External("array"),
            External("deque"),
            // External("flat_map"),
            // External("flat_set"),
            External("forward_list"),
            External("list"),
            External("map"),
            // External("mdspan"),
            External("queue"),
            External("set"),
            External("span"),
            External("stack"),
            External("unordered_map"),
            External("unordered_set"),
            External("vector"),
            External("iterator"),
            // External("generator"),
            External("ranges"),
            External("algorithm"),
            External("execution"),
            External("bit"),
            External("cfenv"),
            External("cmath"),
            External("complex"),
            External("numbers"),
            External("numeric"),
            External("random"),
            External("ratio"),
            External("valarray"),
            // External("stdio"),
            External("fstream"),
            External("iomanip"),
            External("ios"),
            External("iosfwd"),
            // External("strstream"),
            External("regex"),
            External("atomic"),
            External("thread"),
        };

        private Include External(string name) => new(name, IncludeType.External);
    }
}
